name: Deploy CLI to NPM

on:
  release:
    types:
      - released

defaults:
  run:
    working-directory: ./packages/cli

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run build
      - uses: JS-DevTools/npm-publish@19c28f1ef146469e409470805ea4279d47c3d35c
        with:
          package: "./packages/cli/package.json"
          token: ${{ secrets.NPM_TOKEN }}
